[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "simple"
version = "1.0"

[tool.setuptools]
ext-modules = [
  {name = "simple", sources = ["simple.c"]}
]
